name: moldin
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.0.5
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blas=1.0
  - bottleneck=1.3.2
  - brotli=1.0.9
  - ca-certificates=2021.10.8
  - certifi=2021.10.8
  - colorama=0.4.4
  - cycler=0.11.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=0.8.3
  - fonttools=4.25.0
  - freetype=2.10.4
  - icu=58.2
  - intel-openmp=2021.4.0
  - ipykernel=6.9.2
  - ipython=8.1.1
  - jedi=0.18.1
  - jpeg=9d
  - jupyter_client=7.1.2
  - jupyter_core=4.9.2
  - kiwisolver=1.3.2
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.2.0
  - libwebp=1.2.2
  - lz4-c=1.9.3
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - nest-asyncio=1.5.4
  - numexpr=2.8.1
  - numpy=1.21.5
  - numpy-base=1.21.5
  - openssl=1.1.1l
  - packaging=21.3
  - pandas=1.4.1
  - parso=0.8.3
  - pickleshare=0.7.5
  - pillow=9.0.1
  - pip=21.2.4
  - prompt-toolkit=3.0.27
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pygments=2.11.2
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - python=3.9.7
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytz=2021.3
  - pywin32=303
  - pyzmq=22.3.0
  - qt=5.9.7
  - setuptools=58.0.4
  - sip=4.19.13
  - six=1.16.0
  - sqlite=3.38.0
  - stack_data=0.2.0
  - tk=8.6.11
  - tornado=6.1
  - traitlets=5.1.1
  - tzdata=2021e
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - wheel=0.37.1
  - wincertstore=0.2
  - xz=5.2.5
  - zeromq=4.3.4
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - scipy==1.8.0
    - seaborn==0.11.2
